### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by MikhailKamado** [petyasoft/OneWin#9]
Вылезает ошибка:
```
PS C:\Users\mikha\Desktop\OneWin-main> python main.py
              _                               __  _
 _ __    ___ | |_  _   _   __ _  ___   ___   / _|| |_  ___
| '_ \  / _ \| __|| | | | / _` |/ __| / _ \ | |_ | __|/ __|
| |_) ||  __/| |_ | |_| || (_| |\__ \| (_) ||  _|| |_ \__ \
| .__/  \___| \__| \__, | \__,_||___/ \___/ |_|   \__||___/
|_|                |___/


Выберите действие:
1. Начать сбор монет
2. Создать сессию
>1
17:50:00.28 | INFO | Найдено сессий: 2!
17:50:00.28 | INFO | Проверяю сессии на валидность!
17:50:01.44 | SUCCESS | Валидных сессий: 2; Невалидных: 0
17:50:02.11 | ERROR | login | Thread 0 | Fantom | 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://crypto-clicker-backend-go-prod.100hp.app/game/start?user=%7B%22id%22:6668865044,%22first_name%22:%22%F0%9D%94%BD%F0%9D%95%92%F0%9D%95%9F%F0%9D%95%A5%F0%9D%95%A0%F0%9D%95%9E%22,%22last_name%22:%22%22,%22username%22:%22work_fantom%22,%22language_code%22:%22ru%22,%22allows_write_to_pm%22:true%7D&chat_instance=7992270254386242955&chat_type=sender&start_param=refId707649803&auth_date=1723906202&hash=c3035a5c1b9777baff27b20fb14382242ae9a5f03c7ed36891235f80a41a4e9a')
17:50:02.35 | ERROR | login | Thread 1 | Kamado | 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://crypto-clicker-backend-go-prod.100hp.app/game/start?user=%7B%22id%22:5417433533,%22first_name%22:%22Kamado%22,%22last_name%22:%22%22,%22username%22:%22mikhailkamado%22,%22language_code%22:%22ru%22,%22allows_write_to_pm%22:true%7D&chat_instance=4652753660505264562&chat_type=sender&start_param=refId707649803&auth_date=1723906203&hash=68495d04dad3bd4c427a904e0f3ef51d7ec937d9ce3ba1e8967cd16ac854307a')
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022ED879A0E0>
Traceback (most recent call last):
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by MikhailKamado** [comment]
Думаю разрабы изменили ссылку, т.к перейдя по ссылке не открывается игра.
